services:
  pampa-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pampa-app
    ports:
      - "8080:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
    restart: unless-stopped
